### ISSUE TITLE
Sussuro is now in EN too

### ISSUE THREAD

**Issue by nevrending** [legaiabay/legaiabay.github.io#2]
![image](https://user-images.githubusercontent.com/4745298/85051239-da770f00-b1c9-11ea-924c-df7ec3925809.png)

![Screenshot_20200619-021154](https://user-images.githubusercontent.com/4745298/85051270-e236b380-b1c9-11ea-8790-8619e32a7fe1.png)

**Comment by legaiabay** [comment]
oh right missed that one lol fixed

**Comment by nevrending** [comment]
Cool! Thanks!
